import { configure, getRuntimeInfo, isTauri } from "webtau";
import { bootstrapElectrobunFromWindowBridge } from "webtau/adapters/electrobun";
import { getName, getTauriVersion, getVersion, setAppName, setAppVersion } from "webtau/app";
import { createAssetLoader } from "webtau/assets";
import { createAudioController } from "webtau/audio";
import { createInputController, type TouchPoint } from "webtau/input";
import { FALLBACK_MISSION, FALLBACK_THEME, type MissionStubConfig, type ThemeConfig } from "./game/config";
import { startBattlestationRuntime } from "./game/runtime";
import { createDefenseScene } from "./game/scene";

function updateHud(view: import("./services/backend").MissionView): void {
  document.getElementById("mission")!.textContent = view.mission_state;
  document.getElementById("integrity")!.textContent = String(view.integrity);
  document.getElementById("score")!.textContent = String(view.score);
  document.getElementById("tick")!.textContent = String(view.tick);
  document.getElementById("alerts")!.textContent = String(view.alerts);
  document.getElementById("wave")!.textContent = String(view.wave);
  document.getElementById("target")!.textContent =
    view.selected_contact_id === null ? "NONE" : `#${view.selected_contact_id}`;
}

function updateProfileHud(profile: import("./services/profile").OperatorProfile): void {
  document.getElementById("profile")!.textContent =
    `runs ${profile.missionsRun} / best ${profile.bestScore}`;
  document.getElementById("audio-state")!.textContent = profile.muted ? "MUTED" : "ACTIVE";
}

function axisDirection(value: number): number {
  if (value <= -0.45) return -1;
  if (value >= 0.45) return 1;
  return 0;
}

function touchSelectionAxis(touches: TouchPoint[], bounds: DOMRect): number {
  if (touches.length === 0 || bounds.width <= 0) return 0;
  const x = touches[0].x - bounds.left;
  if (x < bounds.width / 3) return -1;
  if (x > (bounds.width * 2) / 3) return 1;
  return 0;
}

function resolveSelectionDirection(...values: number[]): number {
  for (const value of values) {
    const direction = axisDirection(value);
    if (direction !== 0) return direction;
  }
  return 0;
}

async function main() {
  const modeEl = document.getElementById("mode")!;
  const appMetaEl = document.getElementById("app-meta")!;
  const objectiveEl = document.getElementById("objective")!;
  const alertEl = document.getElementById("alert")!;
  const alertLogEl = document.getElementById("alert-log")!;
  const canvas = document.getElementById("radar") as HTMLCanvasElement;

  if (bootstrapElectrobunFromWindowBridge()) {
    const runtime = getRuntimeInfo();
    modeEl.textContent = `Electrobun (${runtime.capabilities.renderMode ?? "browser"})`;
  } else if (!isTauri()) {
    modeEl.textContent = "WASM (web)";
    configure({
      loadWasm: async () => {
        // @ts-ignore - generated by wasm-pack into src/wasm at build time
        const wasm = await import("./wasm/battlestation_wasm");
        await wasm.default();
        wasm.init();
        return wasm;
      },
    });
  } else {
    modeEl.textContent = "Tauri IPC (desktop)";
  }

  setAppName("A130 Defense");
  setAppVersion("0.3.0");
  const [appName, appVersion, tauriVersion] = await Promise.all([
    getName(),
    getVersion(),
    getTauriVersion(),
  ]);
  appMetaEl.textContent = `${appName} v${appVersion} (${tauriVersion})`;

  const assets = createAssetLoader();
  const [mission, theme] = await Promise.all([
    assets.loadJson<MissionStubConfig>("assets/mission-stub.json").catch(() => FALLBACK_MISSION),
    assets.loadJson<ThemeConfig>("assets/battlestation-theme.json").catch(() => FALLBACK_THEME),
  ]);
  objectiveEl.textContent = `${mission.callsign} • ${mission.objective}`;

  const scene = createDefenseScene(canvas, theme.scene);
  const input = createInputController();
  const audio = createAudioController();

  const unlockAudio = () => {
    void audio.resume();
  };
  window.addEventListener("keydown", unlockAudio, { once: true });
  window.addEventListener("pointerdown", unlockAudio, { once: true });

  function screenToLogical(clientX: number, clientY: number): { x: number; y: number } {
    const rect = canvas.getBoundingClientRect();
    return {
      x: ((clientX - rect.left) / rect.width) * 640,
      y: ((clientY - rect.top) / rect.height) * 640,
    };
  }

  const pendingFires: Array<{ x: number; y: number }> = [];
  canvas.style.cursor = "crosshair";
  canvas.addEventListener("pointerdown", (event) => {
    if (event.button === 0) {
      pendingFires.push(screenToLogical(event.clientX, event.clientY));
    }
  });

  const stop = await startBattlestationRuntime({
    mission,
    theme,
    scene,
    audio,
    controls: {
      getSelectionAxis() {
        const bounds = canvas.getBoundingClientRect();
        return resolveSelectionDirection(
          input.keyAxis(["ArrowLeft", "a", "A"], ["ArrowRight", "d", "D"]),
          input.gamepadAxis(0, { deadzone: 0.35 }),
          touchSelectionAxis(input.touches(), bounds),
        );
      },
      getFirePressed() {
        return (
          input.isPressed(" ")
          || input.isPressed("Enter")
          || input.gamepadAxis(5, { deadzone: 0.4 }) > 0.5
        );
      },
      getMutePressed() {
        return input.isPressed("m") || input.isPressed("M");
      },
      drainPointerTargets() {
        return pendingFires.splice(0, pendingFires.length);
      },
      dispose() {
        input.destroy();
      },
    },
    hud: {
      updateMission: updateHud,
      updateProfile: updateProfileHud,
      setAlert(text) {
        alertEl.textContent = text;
      },
      setAlertLog(lines) {
        alertLogEl.textContent = lines.join("\n");
      },
      setStatus() {
        // Browser/Tauri path already exposes a richer HUD overlay.
      },
    },
  });

  window.addEventListener("beforeunload", () => {
    stop();
  });
}

main().catch(console.error);
